Update references to fingerprinted assets in sources
AdamFrey/boot-asset-fingerprint pull request #6
Opened 2017-06-01 15:47 UTC by lsnape

Fixes #5 

The implementation was easier than I thought. However, I have deliberately kept the change as small as possible. Feedback welcome :)

2017-06-02 13:05 UTC, AdamFrey requested changes

2017-06-02 13:05 UTC, AdamFrey commented on src/afrey/boot_asset_fingerprint.clj
> +                      :when (not (contains? (set (map :path sources)) (:path file)))]
You've got an unbalanced square bracket here. You want to delete the last bracket on the line above, I believe

2017-06-02 13:05 UTC, AdamFrey commented
Thanks for this PR! I'm looking over it now

2017-06-02 14:19 UTC, lsnape commented
Sorry about that. Looks like I was a bit overzealous with discarding the hunks pre-commit!

2017-06-04 19:36 UTC, AdamFrey commented
I added your commit, did some work on top of it and pushed it up as 1.4.0. Please check it out and let me know if everything looks good for you.

2017-06-04 19:36 UTC, closed without merging